apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-hppzzv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-hppzzv
    app.kubernetes.io/part-of: jvm-build-suite-application-nmzm
  name: jvm-build-suite-component-hppzzv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-hppzzv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-hppzzv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-pngf-tenant/jvm-build-suite-application-nmzm/jvm-build-suite-component-hppzzv@sha256:c0157057476f0ee4d1800186c9e8f28b97356ff9bf365eb1cb134bc352db992d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
